<!-- include head lines -->
<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
<!-- Meta data for mobile device display -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />
<link href="./style/style.css" rel="stylesheet" type="text/css"/>
<!-- smallDevice.css for small screen device -->
<link href="./style/smallDevice.css" rel="stylesheet" type="text/css" media="only screen and (max-width: 900px), only screen and (max-device-width: 480px)" />
<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>
<script  type="text/javascript" src="./js/main.js" ></script>